export const meetings = [
  {
    id: 1,
    title: "Meet 1",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "2019-01-20",
    amount: 2000,
    total: 4000,
  },
  {
    id: 2,
    title: "Meet 2",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "2019-02-20",
    amount: 1959,
    total: 3918,
  },
  {
    id: 3,
    title: "Meet 3",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "2019-03-20",
    amount: 2470,
    total: 4940,
  },
  {
    id: 4,
    title: "Meet 4",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "2019-04-20",
    amount: 3645,
    total: 7290,
  },
  {
    id: 5,
    title: "Meet 5",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "2019-05-20",
    amount: 1612,
    total: 3224,
  },
  {
    id: 6,
    title: "Meet 6",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "2019-05-20",
    amount: 2002,
    total: 4004,
  },
  {
    id: 7,
    title: "Meet 6",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "2019-02-20",
    amount: 1190,
    total: 2380,
  },
];
